
MMI_SRCS2 = \
      s4win2sacm.c \
      s4adj_time.c \
      s4bcd_dec.c \
      s4blkcut.c \
      s4day_of_year.c \
      s4mkint.c \
      s4get_channel.c \
      s4month_day.c \
      s4newhdr.c \
      s4read_data.c \
      s4read_one_sec.c \
      s4stfind.c \
      s4time_cmp.c \
      s4pickfile_read.c \
      s4winget_smpl.c \
      s4winget_chnl.c \
      s4swap_header.c \
      s4swap4b.c \
      s4win2sac0.c

