
MMI_SRCS2 = \
      v9dewin.c \
      v9adj_time.c \
      v9ctrlc.c \
      v9adj_time2.c \
      v9bcd_dec.c \
      v9bcd_dec8.c \
      v9blkcut.c \
      v9buthip.c \
      v9butlop.c \
      v9butpas.c \
      v9cvt.c \
      v9get_filter.c \
      v9get_channel.c \
      v9print_usage.c \
      v9read_data.c \
      v9read_one_sec.c \
      v9recfil.c \
      v9tandem.c \
      v9swap4b.c \
      v9swap2b.c \
      v9time_cmp.c \

