#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 31 18:27:30 2022

@author: worc4613
"""

    def calc_stalta(self):
        from obspy.signal.trigger import classic_sta_lta
        from datetime import timedelta
        data = self.data
        # stalta = self.stalta
        picks = []
        for i in range(0, len(data)):# , 3):  # stations
            k=0
            #for k in range(0, 3):  # components
            tr = data[i+k]
            # cft = classic_sta_lta(trace.data, int(5 * df), int(10 * df))
            # trigger[j][int(i/3)].append([])
            df = tr.stats.sampling_rate
            cft = classic_sta_lta(tr.data, int(1 * df), int(10 * df))
            for j in range(0, len(cft)):
                if cft[j] > 6 and len(stalta) <= (i+k):
                    stalta.append(j)
                    picks.append(time+timedelta(seconds=(j)/df))
        if self.picks == []:
            self.picks = picks
