
MMI_SRCS2 = \
      y0wadd.c \
      y0adj_time.c \
      y0check.c \
      y0check2.c \
      y0win2fix.c \
      y0adj_time_m.c \
      y0bcd_dec.c \
      y0cptm.c \
      y0elim_ch.c \
      y0get_sysch.c \
      y0get_time.c \
      y0make_skel.c \
      y0read_data_main.c \
      y0read_data_sub.c \
      y0form_write.c \
      y0strcmp2.c \
      y0strncmp2.c \
      y0time_cmp.c \
      y0swap4b.c \
      y0swap2b.c \
      y0werror.c \

