
MMI_SRCS2 = \
      v8wed.c \
      v8get_one_record.c \
      v8adj_time.c \
      v8adj_time2.c \
      v8read_data.c \
      v8bcd_dec.c \
      v8bcd_dec8.c \
      v8time_cmp.c \
      v8select_ch.c \
      v8WinGetVersion.c \
      v8Win2UpkSecSize.c \
      v8Win2UpkSec.c \
      v8ctrlc.c \
      v8Win2UpkCh.c \
      v8_PkSecSub.c \
      v8Win_SetValue.c \
      v8Win_GetValueB.c \
      v8Win_SetValueB.c \
      v8WinGetChSize.c \
      v8WinGetChParam.c \
      v8WinGetChNumber.c \
      v8Win_GetNumber.c \

